server:
  port: 8000
spring:
  datasource:
    name: zkzhu
    url: jdbc:mysql://10.6.0.232:3306/zkzhu
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    fliters: stat
    maxActive: 20
    mixWait: 600000
    minIdel: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/static/dist/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.star.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql